name = "SIR_Model"
uuid = "2fba6350-8549-4ed0-8ebb-22ebb270d193"
authors = ["ProccyBoi <proccyboiofficial@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
